window.DOODLE_DATA = {
  modes: [
    { id:"single", name:"Just a Character", desc:"One little weirdo, no scene." },
    { id:"duo", name:"Character + Friend", desc:"A main character with one tiny buddy." },
    { id:"prop", name:"Character + Prop", desc:"One character with one simple prop." },
    { id:"expression", name:"Faces & Feelings", desc:"Practice clear moods without complex anatomy." },
    { id:"brush", name:"Brush Mini", desc:"Small repetition practice with simple variations." },
    { id:"tiny", name:"Tiny Scene", desc:"Just a character and one tiny anchor object." }
  ],

  doodleQuestCharacters: [
    "pocket ghost",
    "sleepy crescent moon",
    "tiny envelope spirit",
    "round pencil kid",
    "wobbly ink blob",
    "book with little feet",
    "star-shaped baby",
    "crumpled paper gremlin",
    "floating candle face",
    "button-eyed cloud",
    "tiny planet with shoes",
    "shy triangle creature",
    "melty sticker blob",
    "bookmark fairy",
    "teacup ghost",
    "little comet kid",
    "sock-shaped monster",
    "magic eraser creature",
    "square window spirit",
    "sleepy spellbook",
    "tiny receipt goblin",
    "sleepy acorn sprite",
    "bubble tea ghost",
    "paper bag bat",
    "little zipper creature",
    "moonlit spoon spirit",
    "crumbly cookie kid",
    "lost mitten monster",
    "lantern moth doodle",
    "tiny mailbox ghost",
    "puddle blob with eyes",
    "soft cactus kid",
    "paper star wizard",
    "button mushroom baby",
    "tiny snowglobe spirit",
    "ribbon noodle creature",
    "sleepy tape roll",
    "chalk dust sprite",
    "little bottle imp",
    "wandering sock puppet"
  ],

  subjects: {
    single: [
      "pocket ghost",
      "sleepy crescent moon",
      "tiny envelope spirit",
      "round pencil kid",
      "wobbly ink blob",
      "book with little feet",
      "star-shaped baby",
      "crumpled paper gremlin",
      "floating candle face",
      "button-eyed cloud",
      "tiny planet with shoes",
      "shy triangle creature",
      "melty sticker blob",
      "bookmark fairy",
      "teacup ghost",
      "little comet kid",
      "sock-shaped monster",
      "magic eraser creature",
      "square window spirit",
      "sleepy spellbook",
      "tiny receipt goblin",
      "sleepy acorn sprite",
      "bubble tea ghost",
      "paper bag bat",
      "little zipper creature",
      "moonlit spoon spirit",
      "crumbly cookie kid",
      "lost mitten monster",
      "lantern moth doodle",
      "tiny mailbox ghost",
      "puddle blob with eyes",
      "soft cactus kid",
      "paper star wizard",
      "button mushroom baby",
      "tiny snowglobe spirit",
      "ribbon noodle creature",
      "sleepy tape roll",
      "chalk dust sprite",
      "little bottle imp",
      "wandering sock puppet"
    ],
    duo: [
      ["pocket ghost", "tiny key friend"],
      ["sleepy crescent moon", "star crumb"],
      ["tiny envelope spirit", "stamp buddy"],
      ["round pencil kid", "eraser pet"],
      ["wobbly ink blob", "droplet friend"],
      ["book with little feet", "bookmark buddy"],
      ["star-shaped baby", "cloud puff"],
      ["crumpled paper gremlin", "paperclip friend"],
      ["floating candle face", "matchstick buddy"],
      ["button-eyed cloud", "raindrop pet"],
      ["tiny planet with shoes", "moon pebble"],
      ["shy triangle creature", "tiny circle friend"],
      ["melty sticker blob", "glitter dot"],
      ["bookmark fairy", "folded corner friend"],
      ["teacup ghost", "sugar cube buddy"],
      ["little comet kid", "sparkle tail friend"],
      ["sock-shaped monster", "lint ball pet"],
      ["magic eraser creature", "pencil shaving buddy"],
      ["square window spirit", "curtain puff"],
      ["sleepy spellbook", "floating letter friend"],
      ["tiny receipt goblin", "coupon scrap friend"],
      ["sleepy acorn sprite", "leaf blanket buddy"],
      ["bubble tea ghost", "tiny tapioca pet"],
      ["paper bag bat", "sticker moon friend"],
      ["little zipper creature", "button pull buddy"],
      ["moonlit spoon spirit", "sugar sprinkle friend"],
      ["crumbly cookie kid", "milk drop buddy"],
      ["lost mitten monster", "yarn puff pet"],
      ["lantern moth doodle", "glow dot friend"],
      ["tiny mailbox ghost", "postcard buddy"],
      ["puddle blob with eyes", "rain boot friend"],
      ["soft cactus kid", "pebble pal"],
      ["paper star wizard", "tiny wand spark"],
      ["button mushroom baby", "dew drop buddy"],
      ["tiny snowglobe spirit", "snowflake friend"],
      ["ribbon noodle creature", "bow knot buddy"],
      ["sleepy tape roll", "paper strip friend"],
      ["chalk dust sprite", "eraser cloud buddy"],
      ["little bottle imp", "cork cap friend"],
      ["wandering sock puppet", "button nose buddy"]
    ],
    prop: [
      "pocket ghost with a tiny lantern",
      "sleepy crescent moon with a nightcap",
      "tiny envelope spirit with a wax seal",
      "round pencil kid with a little backpack",
      "wobbly ink blob with a tiny crown",
      "book with little feet holding a flower",
      "star-shaped baby with headphones",
      "crumpled paper gremlin with a pencil sword",
      "floating candle face with a ribbon",
      "button-eyed cloud with an umbrella",
      "tiny planet with shoes wearing a scarf",
      "shy triangle creature with a party hat",
      "melty sticker blob with a bandage",
      "bookmark fairy with a paper wand",
      "teacup ghost with a spoon",
      "little comet kid with a tiny flag",
      "sock-shaped monster with a bow tie",
      "magic eraser creature with a dust puff",
      "square window spirit with curtains",
      "sleepy spellbook with glasses",
      "tiny receipt goblin with a tiny coin",
      "sleepy acorn sprite with a leaf cap",
      "bubble tea ghost with a bendy straw",
      "paper bag bat with a sticker patch",
      "little zipper creature with a charm pull",
      "moonlit spoon spirit with a sugar cube",
      "crumbly cookie kid with a jam dot",
      "lost mitten monster with a yarn scarf",
      "lantern moth doodle with a tiny glow jar",
      "tiny mailbox ghost with a postcard",
      "puddle blob with eyes wearing rain boots",
      "soft cactus kid with a little sun hat",
      "paper star wizard with a paper wand",
      "button mushroom baby with a tiny satchel",
      "tiny snowglobe spirit with earmuffs",
      "ribbon noodle creature with a bow tie",
      "sleepy tape roll with a label sticker",
      "chalk dust sprite with a tiny chalk crown",
      "little bottle imp with a cork hat",
      "wandering sock puppet with a loose thread"
    ],
    expression: [
      "nervous pocket ghost",
      "sleepy crescent moon",
      "proud envelope spirit",
      "confused pencil kid",
      "dramatic ink blob",
      "grumpy book with little feet",
      "excited star-shaped baby",
      "shy crumpled paper gremlin",
      "worried candle face",
      "curious button-eyed cloud",
      "brave tiny planet",
      "awkward triangle creature",
      "melty sticker blob feeling embarrassed",
      "smug bookmark fairy",
      "lonely teacup ghost",
      "zoomy little comet kid",
      "suspicious sock monster",
      "cheerful eraser creature",
      "surprised window spirit",
      "peaceful sleepy spellbook",
      "fussy tiny receipt goblin",
      "cozy sleepy acorn sprite",
      "bashful bubble tea ghost",
      "sneaky paper bag bat",
      "startled zipper creature",
      "dreamy moonlit spoon spirit",
      "crumbly cookie kid feeling proud",
      "lost mitten monster feeling hopeful",
      "glowy lantern moth doodle",
      "patient tiny mailbox ghost",
      "puddle blob feeling dramatic",
      "soft cactus kid feeling brave",
      "paper star wizard feeling smug",
      "button mushroom baby feeling curious",
      "tiny snowglobe spirit feeling amazed",
      "ribbon noodle creature feeling awkward",
      "sleepy tape roll feeling grumpy",
      "chalk dust sprite feeling excited",
      "little bottle imp feeling suspicious",
      "wandering sock puppet feeling cheerful"
    ],
    brush: [
      "three tiny ghosts with different faces",
      "four crescent moons with different sleepy eyes",
      "three envelope spirits with different stamps",
      "five blob faces",
      "four pencil kids with different hats",
      "three tiny planets with different rings",
      "four little books with different expressions",
      "five star babies",
      "three crumpled paper gremlins",
      "four candle faces",
      "three cloud heads with button eyes",
      "five triangle creatures",
      "four sticker blobs",
      "three teacup ghosts",
      "four comet kids with different tails",
      "three sock monsters",
      "four eraser creatures",
      "three window spirits",
      "five tiny prop faces",
      "four sleepy object characters",
      "three receipt goblins with different eyebrows",
      "four acorn sprites with different leaf caps",
      "three bubble tea ghosts with different straws",
      "four paper bag bats with different sticker patches",
      "five zipper creature faces",
      "three spoon spirits with different reflections",
      "four cookie kids with different crumb shapes",
      "three mitten monsters with different yarn cuffs",
      "four lantern moth doodles with different glows",
      "three mailbox ghosts with different flags",
      "five puddle blobs with different eye shapes",
      "four cactus kids with different tiny hats",
      "three paper star wizards with different wand sparks",
      "four mushroom babies with different button caps",
      "three snowglobe spirits with different snowflakes",
      "five ribbon noodle creatures",
      "four sleepy tape rolls with different labels",
      "three chalk dust sprites",
      "four little bottle imps with different cork hats",
      "three sock puppets with different loose threads"
    ],
    tiny: [
      "pocket ghost beside a tiny key",
      "crescent moon resting on a cloud puff",
      "envelope spirit sitting near one stamp",
      "pencil kid standing by an eraser",
      "ink blob under one sparkle",
      "book with little feet beside a bookmark",
      "star baby sitting on a pillow",
      "paper gremlin hiding behind a paperclip",
      "candle face glowing beside one match",
      "button-eyed cloud under a tiny umbrella",
      "tiny planet standing on a moon rock",
      "triangle creature beside one circle",
      "sticker blob melting off a sticker sheet",
      "bookmark fairy sitting on a book corner",
      "teacup ghost floating above a saucer",
      "comet kid zooming past one star",
      "sock monster sitting in a laundry pile",
      "eraser creature hiding in pencil dust",
      "window spirit peeking through curtains",
      "spellbook sleeping under one floating letter",
      "receipt goblin sitting beside one tiny coin",
      "acorn sprite napping under one leaf",
      "bubble tea ghost floating above one cup lid",
      "paper bag bat hanging from one sticker moon",
      "zipper creature peeking from one pouch",
      "spoon spirit resting beside one sugar cube",
      "cookie kid sitting on one napkin corner",
      "mitten monster hiding under one yarn puff",
      "lantern moth doodle glowing near one jar",
      "mailbox ghost peeking over one postcard",
      "puddle blob sitting under one raindrop",
      "cactus kid standing beside one pebble",
      "paper star wizard standing on one folded note",
      "mushroom baby sitting under one dew drop",
      "snowglobe spirit floating over one snowflake",
      "ribbon noodle creature curling around one bow",
      "tape roll sleeping beside one paper strip",
      "chalk dust sprite sitting on one chalk line",
      "bottle imp hiding behind one cork",
      "sock puppet leaning on one button"
    ]
  },

  moods: [
    "cozy",
    "sleepy",
    "silly",
    "haunted-cute",
    "gentle",
    "curious",
    "shy",
    "sparkly",
    "brave",
    "soft",
    "wobbly",
    "dreamy",
    "tiny-dramatic",
    "glowy",
    "melty",
    "awkward",
    "floaty",
    "storybook",
    "scribbly",
    "quietly magical"
  ],

  poses: [
    "floating gently",
    "leaning to one side",
    "peeking from behind itself",
    "holding a tiny prop",
    "sitting with tiny feet",
    "waving with one tiny arm",
    "blushing with little cheek marks",
    "drooping like it is tired",
    "standing proudly",
    "hiding behind a tiny object",
    "tilting its face upward",
    "doing a tiny bounce",
    "hugging its buddy",
    "looking at one small thing",
    "wearing something too big"
  ],

  constraints: [
    "Keep it to one small character idea.",
    "No full background needed.",
    "Use one main shape first.",
    "Add one face, one tiny detail, and one optional prop.",
    "Use tiny arms or feet only if they help the character read clearly.",
    "Keep the silhouette simple enough to redraw.",
    "Use 3 colors or fewer.",
    "Do not add extra characters unless the prompt says friend.",
    "Do not add scenery beyond one tiny object or surface.",
    "Stop when the character feels alive enough."
  ],

  hints: {
    single: "Start with one main shape. Let the face do most of the work.",
    duo: "Draw the main character first, then make the buddy much smaller.",
    prop: "Pick one prop that reads clearly and keep the rest simple.",
    expression: "Make the feeling obvious with the eyes, mouth, and tilt of the body.",
    brush: "Repeat the same kind of character with tiny variations instead of adding more stuff.",
    tiny: "Think character plus one anchor object, not a full background."
  },

  steps: {
    single: [
      "Start with one big simple shape.",
      "Add a clear face.",
      "Add one tiny detail or small accessory.",
      "Stop before it gets cluttered."
    ],
    duo: [
      "Draw the main character first.",
      "Add one tiny buddy.",
      "Show their connection with eye direction or pose.",
      "Skip the background unless one tiny object helps."
    ],
    prop: [
      "Sketch the character as one easy silhouette.",
      "Add one readable prop.",
      "Make the prop large enough to notice.",
      "Keep extra details minimal."
    ],
    expression: [
      "Choose the feeling first.",
      "Test a few face options quickly.",
      "Pick the clearest one and redraw it cleanly.",
      "Add simple body language that matches the emotion."
    ],
    brush: [
      "Use one Procreate brush only.",
      "Draw small versions fast.",
      "Change tiny details like eyes, hats, tails, or expressions.",
      "Keep the shapes simple and repeatable."
    ],
    tiny: [
      "Draw the character first.",
      "Add one tiny object or surface.",
      "Use a small grounding line or shadow if needed.",
      "Do not turn it into a full scene."
    ]
  }
};
